
# USERS

GET http://localhost:3003/user/1661692319504
###
GET http://localhost:3003/user/all

###
GET http://localhost:3003/user/?queryName=com
###

POST http://localhost:3003/user
Content-Type: application/json

{
    "name": "Pretinho",
    "nickname": "PretinhoNight",
    "email": "pretinho@pretinho.com"
}

###
PUT http://localhost:3003/user/edit/1661692319504
Content-Type: application/json

{
    "name": "Raquel",
    "nickname": "raqburger",
    "email": "raquelburger@rburger.com"
}

# TASKS

###
POST http://localhost:3003/task
Content-Type: application/json

{
    "title": "Pedir comida",
    "description": "Chamar os humanos as 19h30 para pedir minha janta",
    "limit_date": "29/08/2022",
    "creator_user_id": "1661730292298"
}

###

GET http://localhost:3003/task/1661698095782

###
GET http://localhost:3003/task?creator_user_id=1661714919353